#!/usr/bin/env python3
"""
Data generation script for CODE SPRINT:
- 50+ topics for each of 7 languages (Python, Java, C, C++, JavaScript, SQL, HTML/CSS) -> 350+ topics
- Dedicated worksheets for every single topic with rich coding questions, starter code, hints, test cases
- Rich collection of Coding Challenges categorized by language & difficulty (Easy, Medium, Hard)
"""

import os
import json

# 1. TOPIC DEFINITIONS FOR EACH LANGUAGE (50 topics each)
LANG_TOPICS = {
    "python": [
        # Beginner (1-18)
        ("py-001", "Introduction to Python & Setup", "Basics & Fundamentals", "Beginner"),
        ("py-002", "Variables, Data Types & Type Casting", "Basics & Fundamentals", "Beginner"),
        ("py-003", "Arithmetic & Assignment Operators", "Operators & Expressions", "Beginner"),
        ("py-004", "Comparison & Logical Operators", "Operators & Expressions", "Beginner"),
        ("py-005", "User Input with input() & String Conversion", "I/O Operations", "Beginner"),
        ("py-006", "String Basics, Indexing & Slicing", "Strings", "Beginner"),
        ("py-007", "String Methods & Formatting (f-strings)", "Strings", "Beginner"),
        ("py-008", "Conditional Statements (if, elif, else)", "Control Flow", "Beginner"),
        ("py-009", "Nested Conditionals & Ternary Operator", "Control Flow", "Beginner"),
        ("py-010", "While Loops & Counter Incrementation", "Loops & Iteration", "Beginner"),
        ("py-011", "For Loops & the range() Function", "Loops & Iteration", "Beginner"),
        ("py-012", "Loop Control (break, continue, pass)", "Loops & Iteration", "Beginner"),
        ("py-013", "Nested Loops & Pattern Printing", "Loops & Iteration", "Beginner"),
        ("py-014", "Defining Functions with def & Parameters", "Functions", "Beginner"),
        ("py-015", "Return Values & Multiple Returns", "Functions", "Beginner"),
        ("py-016", "Default Arguments & Keyword Arguments", "Functions", "Beginner"),
        ("py-017", "Scope: Local vs Global Variables", "Functions", "Beginner"),
        ("py-018", "Built-in Functions (len, min, max, sum, abs)", "Built-ins", "Beginner"),
        # Intermediate (19-35)
        ("py-019", "Python Lists: Creation, Indexing & Operations", "Data Structures", "Intermediate"),
        ("py-020", "List Methods (append, extend, insert, pop, remove)", "Data Structures", "Intermediate"),
        ("py-021", "List Slicing & List Comprehensions", "Data Structures", "Intermediate"),
        ("py-022", "Tuples: Immutability & Tuple Packing/Unpacking", "Data Structures", "Intermediate"),
        ("py-023", "Dictionaries: Keys, Values & Key-Value Pairs", "Data Structures", "Intermediate"),
        ("py-024", "Dictionary Methods & Iteration (keys, items, values)", "Data Structures", "Intermediate"),
        ("py-025", "Dictionary Comprehensions & Nested Dicts", "Data Structures", "Intermediate"),
        ("py-026", "Sets & Set Operations (union, intersection, diff)", "Data Structures", "Intermediate"),
        ("py-027", "Lambda Functions & Anonymous Callables", "Functional Programming", "Intermediate"),
        ("py-028", "Higher-Order Functions (map, filter, sorted)", "Functional Programming", "Intermediate"),
        ("py-029", "Arbitrary Arguments (*args and **kwargs)", "Functions", "Intermediate"),
        ("py-030", "File I/O: Reading Text Files (open, with)", "File Handling", "Intermediate"),
        ("py-031", "File I/O: Writing and Appending Files", "File Handling", "Intermediate"),
        ("py-032", "Exception Handling (try, except, else, finally)", "Error Handling", "Intermediate"),
        ("py-033", "Raising Custom Exceptions (raise)", "Error Handling", "Intermediate"),
        ("py-034", "Modules & Imports (math, random, sys, os)", "Modules & Packages", "Intermediate"),
        ("py-035", "Working with JSON Data (json.loads, json.dumps)", "Data Serialization", "Intermediate"),
        # Advanced (36-50)
        ("py-036", "Classes & Object-Oriented Basics (__init__, self)", "OOP", "Advanced"),
        ("py-037", "Instance vs Class Variables and Methods", "OOP", "Advanced"),
        ("py-038", "OOP Inheritance & super() Method", "OOP", "Advanced"),
        ("py-039", "Multiple Inheritance & Method Resolution Order (MRO)", "OOP", "Advanced"),
        ("py-040", "Encapsulation & Private Attributes (_ and __)", "OOP", "Advanced"),
        ("py-041", "Polymorphism & Method Overriding", "OOP", "Advanced"),
        ("py-042", "Special Dunder Methods (__str__, __repr__, __len__, __eq__)", "OOP", "Advanced"),
        ("py-043", "Decorators & Function Wrappers (@decorator)", "Advanced Concepts", "Advanced"),
        ("py-044", "Decorators with Arguments & Chaining", "Advanced Concepts", "Advanced"),
        ("py-045", "Generators & the yield Keyword", "Advanced Concepts", "Advanced"),
        ("py-046", "Iterators & the Iteration Protocol (__iter__, __next__)", "Advanced Concepts", "Advanced"),
        ("py-047", "Context Managers & custom __enter__ / __exit__", "Advanced Concepts", "Advanced"),
        ("py-048", "Regular Expressions with the re Module", "Text Processing", "Advanced"),
        ("py-049", "Concurrency Basics: Threading and Multiprocessing", "Concurrency", "Advanced"),
        ("py-050", "Asyncio & Async / Await Coroutines", "Asynchronous Programming", "Advanced"),
    ],
    "java": [
        # Beginner (1-18)
        ("java-001", "Introduction to Java, JVM, JRE & JDK", "Basics & Fundamentals", "Beginner"),
        ("java-002", "Java Program Structure & main() Method", "Basics & Fundamentals", "Beginner"),
        ("java-003", "Primitive Data Types (int, double, char, boolean)", "Basics & Fundamentals", "Beginner"),
        ("java-004", "Variables, Constants (final) & Type Casting", "Basics & Fundamentals", "Beginner"),
        ("java-005", "Arithmetic, Relational & Logical Operators", "Operators", "Beginner"),
        ("java-006", "Reading User Input with Scanner", "I/O", "Beginner"),
        ("java-007", "If, Else If, and Else Conditionals", "Control Flow", "Beginner"),
        ("java-008", "Switch-Case Statements & Enhancements", "Control Flow", "Beginner"),
        ("java-009", "Ternary Operator in Java", "Control Flow", "Beginner"),
        ("java-010", "While Loops & Do-While Loops", "Loops", "Beginner"),
        ("java-011", "Standard For Loops & Loop Iterations", "Loops", "Beginner"),
        ("java-012", "Break and Continue Statements", "Loops", "Beginner"),
        ("java-013", "Nested Loops & Triangular Patterns", "Loops", "Beginner"),
        ("java-014", "Defining Methods, Parameters & Return Types", "Methods", "Beginner"),
        ("java-015", "Method Overloading in Java", "Methods", "Beginner"),
        ("java-016", "Variable Scope & Pass-by-Value", "Methods", "Beginner"),
        ("java-017", "1D Arrays: Declaration, Allocation & Traversal", "Arrays", "Beginner"),
        ("java-018", "Enhanced For Loop (For-Each) with Arrays", "Arrays", "Beginner"),
        # Intermediate (19-35)
        ("java-019", "Multidimensional 2D Arrays & Matrices", "Arrays", "Intermediate"),
        ("java-020", "String Class & Immutability", "Strings", "Intermediate"),
        ("java-021", "String Methods (substring, indexOf, replace, split)", "Strings", "Intermediate"),
        ("java-022", "StringBuilder and StringBuffer for Mutation", "Strings", "Intermediate"),
        ("java-023", "Classes, Objects & new Keyword", "OOP", "Intermediate"),
        ("java-024", "Constructors & Default vs Parameterized", "OOP", "Intermediate"),
        ("java-025", "this Keyword and Constructor Chaining", "OOP", "Intermediate"),
        ("java-026", "Access Modifiers (public, private, protected, default)", "OOP", "Intermediate"),
        ("java-027", "Encapsulation & Getters/Setters", "OOP", "Intermediate"),
        ("java-028", "static Variables, Methods & Blocks", "OOP", "Intermediate"),
        ("java-029", "Inheritance with extends & super Keyword", "OOP", "Intermediate"),
        ("java-030", "Method Overriding & @Override Annotation", "OOP", "Intermediate"),
        ("java-031", "Polymorphism: Dynamic Method Dispatch", "OOP", "Intermediate"),
        ("java-032", "Abstract Classes & Abstract Methods", "OOP", "Intermediate"),
        ("java-033", "Interfaces & Multiple Inheritance of Types", "OOP", "Intermediate"),
        ("java-034", "Default and Static Methods in Interfaces", "OOP", "Intermediate"),
        ("java-035", "Packages & Classpath Management", "OOP", "Intermediate"),
        # Advanced (36-50)
        ("java-036", "Exception Handling with try-catch-finally", "Exceptions", "Advanced"),
        ("java-037", "Throw, Throws & Custom Checked/Unchecked Exceptions", "Exceptions", "Advanced"),
        ("java-038", "Java Generics: Generic Classes & Methods", "Generics", "Advanced"),
        ("java-039", "Wildcards in Generics (? extends / ? super)", "Generics", "Advanced"),
        ("java-040", "Collections Framework Overview & List (ArrayList, LinkedList)", "Collections", "Advanced"),
        ("java-041", "Set Interface (HashSet, TreeSet, LinkedHashSet)", "Collections", "Advanced"),
        ("java-042", "Map Interface (HashMap, TreeMap, LinkedHashMap)", "Collections", "Advanced"),
        ("java-043", "Queue, Deque & PriorityQueue", "Collections", "Advanced"),
        ("java-044", "Comparable and Comparator Interfaces", "Collections", "Advanced"),
        ("java-045", "Lambda Expressions & Functional Interfaces", "Modern Java", "Advanced"),
        ("java-046", "Stream API (filter, map, reduce, collect)", "Modern Java", "Advanced"),
        ("java-047", "Optional Class & Null-Safety", "Modern Java", "Advanced"),
        ("java-048", "File I/O: FileReader, FileWriter & BufferedReader", "I/O & NIO", "Advanced"),
        ("java-049", "Multithreading Basics (Thread class, Runnable)", "Concurrency", "Advanced"),
        ("java-050", "Synchronization, Locks & Thread Safety", "Concurrency", "Advanced"),
    ],
    "c": [
        # Beginner (1-18)
        ("c-001", "Introduction to C, Compilers & #include <stdio.h>", "Basics", "Beginner"),
        ("c-002", "Variables, Data Types (int, float, char, double)", "Basics", "Beginner"),
        ("c-003", "Constants, #define & const Qualifier", "Basics", "Beginner"),
        ("c-004", "printf() Format Specifiers (%d, %f, %c, %s, %p)", "I/O", "Beginner"),
        ("c-005", "scanf() User Input & the Address-of Operator (&)", "I/O", "Beginner"),
        ("c-006", "Arithmetic, Increment & Decrement Operators", "Operators", "Beginner"),
        ("c-007", "Relational, Equality & Logical Operators", "Operators", "Beginner"),
        ("c-008", "Bitwise Operators (&, |, ^, ~, <<, >>)", "Operators", "Beginner"),
        ("c-009", "If, Else If, and Else Decisions", "Control Flow", "Beginner"),
        ("c-010", "Nested Conditions & Ternary Operator (?:)", "Control Flow", "Beginner"),
        ("c-011", "Switch-Case Statements & Break Mechanism", "Control Flow", "Beginner"),
        ("c-012", "While Loops & Loop Invariants", "Loops", "Beginner"),
        ("c-013", "Do-While Loops & Post-Condition Checking", "Loops", "Beginner"),
        ("c-014", "For Loops & Iteration Control", "Loops", "Beginner"),
        ("c-015", "Break, Continue & Goto Statements", "Loops", "Beginner"),
        ("c-016", "Nested Loops & Pattern Generation", "Loops", "Beginner"),
        ("c-017", "Functions: Declaration, Definition & Return Types", "Functions", "Beginner"),
        ("c-018", "Function Prototypes & Header Files", "Functions", "Beginner"),
        # Intermediate (19-35)
        ("c-019", "Scope of Variables: Local, Global & static", "Functions", "Intermediate"),
        ("c-020", "Recursion & Call Stack Mechanics", "Functions", "Intermediate"),
        ("c-021", "1D Arrays: Memory Layout, Indexing & Traversal", "Arrays", "Intermediate"),
        ("c-022", "Passing Arrays to Functions", "Arrays", "Intermediate"),
        ("c-023", "2D Arrays & Matrix Mathematics", "Arrays", "Intermediate"),
        ("c-024", "Strings in C: Null-Terminated Character Arrays", "Strings", "Intermediate"),
        ("c-025", "String Library Functions (strlen, strcpy, strcat, strcmp)", "Strings", "Intermediate"),
        ("c-026", "Pointer Fundamentals: Addresses, Values & Dereferencing (*)", "Pointers", "Intermediate"),
        ("c-027", "Pointer Arithmetic & Array Pointer Relationship", "Pointers", "Intermediate"),
        ("c-028", "Pass by Reference using Pointers", "Pointers", "Intermediate"),
        ("c-029", "Pointers to Pointers (Double Pointers **ptr)", "Pointers", "Intermediate"),
        ("c-030", "Structures (struct): Defining & Accessing Members", "Structures", "Intermediate"),
        ("c-031", "Nested Structures & Arrays of Structures", "Structures", "Intermediate"),
        ("c-032", "Structure Pointers & the Arrow Operator (->)", "Structures", "Intermediate"),
        ("c-033", "Typedef Keyword for Alias Definition", "Structures", "Intermediate"),
        ("c-034", "Unions (union) & Memory Sharing", "Structures", "Intermediate"),
        ("c-035", "Enumerations (enum) & Integer Constants", "Structures", "Intermediate"),
        # Advanced (36-50)
        ("c-036", "Dynamic Memory Allocation: malloc() & free()", "Memory Management", "Advanced"),
        ("c-037", "calloc() and realloc() for Buffer Resizing", "Memory Management", "Advanced"),
        ("c-038", "Memory Leaks, Dangling Pointers & Valgrind Concepts", "Memory Management", "Advanced"),
        ("c-039", "File Operations: fopen(), fclose(), modes (r, w, a)", "File Handling", "Advanced"),
        ("c-040", "Formatted File I/O: fprintf() and fscanf()", "File Handling", "Advanced"),
        ("c-041", "Binary File I/O: fread() and fwrite()", "File Handling", "Advanced"),
        ("c-042", "File Positioning: fseek(), ftell(), rewind()", "File Handling", "Advanced"),
        ("c-043", "Function Pointers: Callbacks & Dispatch Tables", "Advanced Pointers", "Advanced"),
        ("c-044", "Command Line Arguments (argc, argv)", "System Programming", "Advanced"),
        ("c-045", "Pre-processor Directives (#define, #ifdef, #pragma)", "Preprocessor", "Advanced"),
        ("c-046", "Macros with Arguments vs Inline Functions", "Preprocessor", "Advanced"),
        ("c-047", "Bit Fields in Structures for Hardware Packing", "System Programming", "Advanced"),
        ("c-048", "Volatile and Const Qualifiers in Embedded Systems", "System Programming", "Advanced"),
        ("c-049", "Linked Lists Implementation in C", "Data Structures", "Advanced"),
        ("c-050", "Stack and Queue Data Structures from Scratch", "Data Structures", "Advanced"),
    ],
    "cpp": [
        # Beginner (1-18)
        ("cpp-001", "Introduction to C++ & Modern C++ Standards", "Basics", "Beginner"),
        ("cpp-002", "Streams & I/O: std::cout, std::cin, std::endl", "I/O", "Beginner"),
        ("cpp-003", "Data Types, auto Type Inference & Type Modifiers", "Basics", "Beginner"),
        ("cpp-004", "Constants (const, constexpr) in C++", "Basics", "Beginner"),
        ("cpp-005", "Operators in C++ (Arithmetic, Relational, Logical)", "Operators", "Beginner"),
        ("cpp-006", "Conditional Statements (if, else if, else)", "Control Flow", "Beginner"),
        ("cpp-007", "Switch-Case & [[fallthrough]]", "Control Flow", "Beginner"),
        ("cpp-008", "While and Do-While Iterations", "Loops", "Beginner"),
        ("cpp-009", "For Loops & Range-Based For Loops", "Loops", "Beginner"),
        ("cpp-010", "Functions, Prototypes & Return Types", "Functions", "Beginner"),
        ("cpp-011", "Default Arguments in C++ Functions", "Functions", "Beginner"),
        ("cpp-012", "Function Overloading & Signature Matching", "Functions", "Beginner"),
        ("cpp-013", "Inline Functions and Compiler Inlining", "Functions", "Beginner"),
        ("cpp-014", "References in C++ (&ref) vs Pointers", "References & Pointers", "Beginner"),
        ("cpp-015", "Passing by Value, by Reference & by Const Reference", "Functions", "Beginner"),
        ("cpp-016", "Pointers Basics, Nullptr & Dereferencing", "References & Pointers", "Beginner"),
        ("cpp-017", "Standard Arrays & std::array Container", "Arrays", "Beginner"),
        ("cpp-018", "Introduction to std::string & String Operations", "Strings", "Beginner"),
        # Intermediate (19-35)
        ("cpp-019", "Classes and Objects: Encapsulation & Access Specifiers", "OOP", "Intermediate"),
        ("cpp-020", "Constructors, Member Initializer Lists & Destructors", "OOP", "Intermediate"),
        ("cpp-021", "Copy Constructors & Deep vs Shallow Copy", "OOP", "Intermediate"),
        ("cpp-022", "this Pointer in Member Methods", "OOP", "Intermediate"),
        ("cpp-023", "Static Members (static variables and static methods)", "OOP", "Intermediate"),
        ("cpp-024", "Friend Functions and Friend Classes", "OOP", "Intermediate"),
        ("cpp-025", "Inheritance: Public, Protected & Private", "OOP", "Intermediate"),
        ("cpp-026", "Constructor and Destructor Order in Inheritance", "OOP", "Intermediate"),
        ("cpp-027", "Polymorphism: Virtual Functions & Virtual Destructors", "OOP", "Intermediate"),
        ("cpp-028", "Pure Virtual Functions & Abstract Base Classes", "OOP", "Intermediate"),
        ("cpp-029", "Operator Overloading (+, -, ==, <<, >>)", "OOP", "Intermediate"),
        ("cpp-030", "Dynamic Memory Allocation with new and delete", "Memory", "Intermediate"),
        ("cpp-031", "Introduction to STL: std::vector Operations", "STL", "Intermediate"),
        ("cpp-032", "STL std::pair and std::tuple", "STL", "Intermediate"),
        ("cpp-033", "STL Iterators: begin(), end(), rbegin(), rend()", "STL", "Intermediate"),
        ("cpp-034", "STL std::list and std::deque", "STL", "Intermediate"),
        ("cpp-035", "STL std::set and std::unordered_set", "STL", "Intermediate"),
        # Advanced (36-50)
        ("cpp-036", "STL std::map and std::unordered_map", "STL", "Advanced"),
        ("cpp-037", "STL std::stack, std::queue & std::priority_queue", "STL", "Advanced"),
        ("cpp-038", "STL Algorithms (std::sort, std::find, std::binary_search)", "STL", "Advanced"),
        ("cpp-039", "Function Templates & Template Specialization", "Templates", "Advanced"),
        ("cpp-040", "Class Templates in C++", "Templates", "Advanced"),
        ("cpp-041", "Exception Handling with try, catch & throw", "Exceptions", "Advanced"),
        ("cpp-042", "RAII (Resource Acquisition Is Initialization)", "Modern C++", "Advanced"),
        ("cpp-043", "Smart Pointers: std::unique_ptr", "Modern C++", "Advanced"),
        ("cpp-044", "Smart Pointers: std::shared_ptr and std::weak_ptr", "Modern C++", "Advanced"),
        ("cpp-045", "Lambda Expressions & Capture Clauses ([&], [=])", "Modern C++", "Advanced"),
        ("cpp-046", "Rvalue References (&&) & Move Semantics", "Modern C++", "Advanced"),
        ("cpp-047", "std::move and Move Constructors", "Modern C++", "Advanced"),
        ("cpp-048", "File Streams: std::ifstream, std::ofstream, std::fstream", "I/O", "Advanced"),
        ("cpp-049", "Namespaces and Anonymous Namespaces", "Modern C++", "Advanced"),
        ("cpp-050", "Multithreading with std::thread and std::mutex", "Concurrency", "Advanced"),
    ],
    "javascript": [
        # Beginner (1-18)
        ("js-001", "Introduction to JavaScript, Engines & console.log", "Basics", "Beginner"),
        ("js-002", "Variables: var, let, const & Block Scope", "Basics", "Beginner"),
        ("js-003", "Data Types: Primitives (number, string, boolean, null, undefined, symbol, bigint)", "Basics", "Beginner"),
        ("js-004", "Arithmetic & Assignment Operators", "Operators", "Beginner"),
        ("js-005", "Comparison Operators: Strict (===) vs Loose (==)", "Operators", "Beginner"),
        ("js-006", "Logical Operators (&&, ||, !) & Nullish Coalescing (??)", "Operators", "Beginner"),
        ("js-007", "Strings, Concatenation & Template Literals (`${}`)", "Strings", "Beginner"),
        ("js-008", "String Methods (slice, substring, replace, split, trim)", "Strings", "Beginner"),
        ("js-009", "If, Else If, and Else Conditionals", "Control Flow", "Beginner"),
        ("js-010", "Ternary Operator & Short-Circuit Evaluation", "Control Flow", "Beginner"),
        ("js-011", "Switch-Case Statements", "Control Flow", "Beginner"),
        ("js-012", "While and Do-While Loops", "Loops", "Beginner"),
        ("js-013", "For Loops & Loop Counters", "Loops", "Beginner"),
        ("js-014", "For...of (iterables) and For...in (objects)", "Loops", "Beginner"),
        ("js-015", "Functions: Declaration vs Expression", "Functions", "Beginner"),
        ("js-016", "Arrow Functions (() => {}) & Lexical this", "Functions", "Beginner"),
        ("js-017", "Default Parameters & Rest Parameters (...args)", "Functions", "Beginner"),
        ("js-018", "Scope: Global, Function, Block & Hoisting", "Functions", "Beginner"),
        # Intermediate (19-35)
        ("js-019", "Arrays: Creation, Indexing & Length", "Arrays", "Intermediate"),
        ("js-020", "Array Methods: push, pop, shift, unshift", "Arrays", "Intermediate"),
        ("js-021", "Array Slicing & Splicing (slice vs splice)", "Arrays", "Intermediate"),
        ("js-022", "Array Higher-Order Methods: map, filter, reduce", "Arrays", "Intermediate"),
        ("js-023", "Array Search: find, findIndex, includes, indexOf", "Arrays", "Intermediate"),
        ("js-024", "Objects: Object Literals, Properties & Dot/Bracket Notation", "Objects", "Intermediate"),
        ("js-025", "Object Methods, this Keyword & Object.keys/values/entries", "Objects", "Intermediate"),
        ("js-026", "Destructuring Assignment (Arrays & Objects)", "Modern JS", "Intermediate"),
        ("js-027", "Spread Operator (...) with Arrays and Objects", "Modern JS", "Intermediate"),
        ("js-028", "Set and Map Built-in Data Structures", "Data Structures", "Intermediate"),
        ("js-029", "JSON Parsing and Stringification (JSON.parse, JSON.stringify)", "Data Handling", "Intermediate"),
        ("js-030", "Error Handling with try, catch, finally & throw", "Error Handling", "Intermediate"),
        ("js-031", "DOM Selection: getElementById, querySelector, querySelectorAll", "DOM", "Intermediate"),
        ("js-032", "DOM Manipulation: textContent, innerHTML, classList", "DOM", "Intermediate"),
        ("js-033", "DOM Events & addEventListener (click, input, submit)", "DOM", "Intermediate"),
        ("js-034", "Event Bubbling, Capturing & event.stopPropagation()", "DOM", "Intermediate"),
        ("js-035", "Timer Functions: setTimeout & setInterval", "Async JS", "Intermediate"),
        # Advanced (36-50)
        ("js-036", "Synchronous vs Asynchronous JavaScript & the Event Loop", "Async JS", "Advanced"),
        ("js-037", "Callbacks & the Callback Hell Pattern", "Async JS", "Advanced"),
        ("js-038", "Promises: Creating, Resolving, Rejecting & Chaining", "Async JS", "Advanced"),
        ("js-039", "Promise Combinators: all, race, allSettled, any", "Async JS", "Advanced"),
        ("js-040", "Async / Await Syntax & Async Error Handling", "Async JS", "Advanced"),
        ("js-041", "Fetch API for Network Requests", "Networking", "Advanced"),
        ("js-042", "Closures & Lexical Scoping in Depth", "Advanced Concepts", "Advanced"),
        ("js-043", "Prototypal Inheritance & Object.prototype", "OOP", "Advanced"),
        ("js-044", "ES6 Classes, Constructors & extends Keyword", "OOP", "Advanced"),
        ("js-045", "Getters, Setters & Static Methods in Classes", "OOP", "Advanced"),
        ("js-046", "Modules: ES Modules (import / export) vs CommonJS (require)", "Modular JS", "Advanced"),
        ("js-047", "Currying and Function Composition", "Functional JS", "Advanced"),
        ("js-048", "Debouncing and Throttling for UI Performance", "Optimization", "Advanced"),
        ("js-049", "Generators (function*) and Iterators in JS", "Advanced Concepts", "Advanced"),
        ("js-050", "Web Storage: localStorage, sessionStorage & Cookies", "Browser APIs", "Advanced"),
    ],
    "sql": [
        # Beginner (1-18)
        ("sql-001", "Introduction to Relational Databases & SQL Overview", "Basics", "Beginner"),
        ("sql-002", "SELECT Statement & Retrieving All Columns (*)", "Querying", "Beginner"),
        ("sql-003", "Selecting Specific Columns & Column Aliasing (AS)", "Querying", "Beginner"),
        ("sql-004", "SELECT DISTINCT & Eliminating Duplicate Rows", "Querying", "Beginner"),
        ("sql-005", "Filtering Rows with the WHERE Clause", "Filtering", "Beginner"),
        ("sql-006", "Comparison Operators (=, <>, <, >, <=, >=)", "Filtering", "Beginner"),
        ("sql-007", "Logical Operators: AND, OR, and NOT", "Filtering", "Beginner"),
        ("sql-008", "The BETWEEN and NOT BETWEEN Range Operators", "Filtering", "Beginner"),
        ("sql-009", "The IN and NOT IN Membership Operators", "Filtering", "Beginner"),
        ("sql-010", "Pattern Matching with LIKE & Wildcards (%, _)", "Filtering", "Beginner"),
        ("sql-011", "Handling Missing Data with IS NULL & IS NOT NULL", "Filtering", "Beginner"),
        ("sql-012", "Sorting Results with ORDER BY (ASC / DESC)", "Sorting & Pagination", "Beginner"),
        ("sql-013", "Multi-Column Sorting in ORDER BY", "Sorting & Pagination", "Beginner"),
        ("sql-014", "Limiting Results with LIMIT and OFFSET", "Sorting & Pagination", "Beginner"),
        ("sql-015", "Aggregate Function: COUNT()", "Aggregations", "Beginner"),
        ("sql-016", "Aggregate Functions: SUM() and AVG()", "Aggregations", "Beginner"),
        ("sql-017", "Aggregate Functions: MIN() and MAX()", "Aggregations", "Beginner"),
        ("sql-018", "Mathematical Scalar Functions (ROUND, ABS, CEIL, FLOOR)", "Scalar Functions", "Beginner"),
        # Intermediate (19-35)
        ("sql-019", "String Scalar Functions (UPPER, LOWER, LENGTH, SUBSTR)", "Scalar Functions", "Intermediate"),
        ("sql-020", "Date and Time Functions (DATE, TIME, STRFTIME)", "Scalar Functions", "Intermediate"),
        ("sql-021", "Grouping Data with GROUP BY", "Aggregations", "Intermediate"),
        ("sql-022", "Filtering Groups with the HAVING Clause", "Aggregations", "Intermediate"),
        ("sql-023", "WHERE vs HAVING Differences & Best Practices", "Aggregations", "Intermediate"),
        ("sql-024", "Introduction to Relational Joins & Foreign Keys", "Joins", "Intermediate"),
        ("sql-025", "INNER JOIN: Combining Matching Records", "Joins", "Intermediate"),
        ("sql-026", "LEFT JOIN: Preserving Left Table Records", "Joins", "Intermediate"),
        ("sql-027", "RIGHT JOIN and FULL OUTER JOIN Concepts", "Joins", "Intermediate"),
        ("sql-028", "CROSS JOIN and Cartesian Products", "Joins", "Intermediate"),
        ("sql-029", "Self Joins: Joining a Table to Itself", "Joins", "Intermediate"),
        ("sql-030", "Multiple Table Joins (3+ Tables)", "Joins", "Intermediate"),
        ("sql-031", "Set Operations: UNION and UNION ALL", "Set Operations", "Intermediate"),
        ("sql-032", "Set Operations: INTERSECT and EXCEPT", "Set Operations", "Intermediate"),
        ("sql-033", "Conditional Logic with CASE WHEN Statements", "Advanced Querying", "Intermediate"),
        ("sql-034", "COALESCE and IFNULL Functions for Fallback Values", "Advanced Querying", "Intermediate"),
        ("sql-035", "INSERT INTO: Inserting Single & Multiple Rows", "Data Modification", "Intermediate"),
        # Advanced (36-50)
        ("sql-036", "UPDATE Statement with WHERE Filter", "Data Modification", "Advanced"),
        ("sql-037", "DELETE Statement & Truncation Concepts", "Data Modification", "Advanced"),
        ("sql-038", "CREATE TABLE: Schema Definition & Data Types", "DDL", "Advanced"),
        ("sql-039", "Table Constraints (PRIMARY KEY, NOT NULL, UNIQUE, CHECK, DEFAULT)", "DDL", "Advanced"),
        ("sql-040", "FOREIGN KEY Constraints & Referential Integrity (ON DELETE CASCADE)", "DDL", "Advanced"),
        ("sql-041", "ALTER TABLE: Adding, Renaming & Dropping Columns", "DDL", "Advanced"),
        ("sql-042", "DROP TABLE vs TRUNCATE TABLE", "DDL", "Advanced"),
        ("sql-043", "Subqueries: Scalar & Single-Row Subqueries", "Subqueries", "Advanced"),
        ("sql-044", "Subqueries with IN, ANY, and ALL", "Subqueries", "Advanced"),
        ("sql-045", "Correlated Subqueries & EXISTS / NOT EXISTS", "Subqueries", "Advanced"),
        ("sql-046", "Common Table Expressions (CTEs) with WITH Clause", "Advanced Querying", "Advanced"),
        ("sql-047", "Window Functions: OVER(), PARTITION BY, ORDER BY", "Window Functions", "Advanced"),
        ("sql-048", "Window Ranking Functions (ROW_NUMBER, RANK, DENSE_RANK)", "Window Functions", "Advanced"),
        ("sql-049", "Database Indexes (CREATE INDEX) & Query Performance", "Performance", "Advanced"),
        ("sql-050", "Database Transactions: COMMIT, ROLLBACK & ACID Properties", "Transactions", "Advanced"),
    ],
    "html-css": [
        # Beginner (1-18)
        ("html-001", "Introduction to HTML, Tags, Elements & Attributes", "HTML Basics", "Beginner"),
        ("html-002", "HTML Document Structure (<!DOCTYPE>, <html>, <head>, <body>)", "HTML Basics", "Beginner"),
        ("html-003", "Heading Tags (<h1> to <h6>) & Typography Hierarchy", "HTML Text", "Beginner"),
        ("html-004", "Paragraphs (<p>), Line Breaks (<br>), and Horizontal Rules (<hr>)", "HTML Text", "Beginner"),
        ("html-005", "Text Formatting (<strong>, <em>, <mark>, <small>, <code>)", "HTML Text", "Beginner"),
        ("html-006", "Hyperlinks (<a>), href Attribute & Target (_blank)", "HTML Links", "Beginner"),
        ("html-007", "Images (<img>), src, alt Attributes & Responsive Width", "HTML Media", "Beginner"),
        ("html-008", "Unordered Lists (<ul>) and Ordered Lists (<ol>)", "HTML Lists", "Beginner"),
        ("html-009", "HTML Tables (<table>, <tr>, <th>, <td>)", "HTML Tables", "Beginner"),
        ("html-010", "HTML Forms (<form>, action, method)", "HTML Forms", "Beginner"),
        ("html-011", "Form Inputs (<input type='text', 'password', 'email', 'number'>)", "HTML Forms", "Beginner"),
        ("html-012", "Buttons, Checkboxes, and Radio Buttons", "HTML Forms", "Beginner"),
        ("html-013", "Textareas & Dropdown Select (<select>, <option>)", "HTML Forms", "Beginner"),
        ("html-014", "Semantic HTML5 (<header>, <nav>, <main>, <section>, <article>, <footer>)", "HTML Semantics", "Beginner"),
        ("html-015", "Introduction to CSS: Inline, Internal & External Styles", "CSS Basics", "Beginner"),
        ("html-016", "CSS Selectors: Element, Class (.), and ID (#)", "CSS Basics", "Beginner"),
        ("html-017", "CSS Colors (Hex, RGB, HSL) & Backgrounds", "CSS Styling", "Beginner"),
        ("html-018", "CSS Typography (font-family, font-size, font-weight, line-height)", "CSS Styling", "Beginner"),
        # Intermediate (19-35)
        ("html-019", "The CSS Box Model: Content, Padding, Border, Margin", "CSS Box Model", "Intermediate"),
        ("html-020", "box-sizing: border-box vs content-box", "CSS Box Model", "Intermediate"),
        ("html-021", "CSS Display Property (block, inline, inline-block, none)", "CSS Layout", "Intermediate"),
        ("html-022", "CSS Positioning: static, relative, absolute, fixed, sticky", "CSS Layout", "Intermediate"),
        ("html-023", "Z-Index & Stacking Contexts", "CSS Layout", "Intermediate"),
        ("html-024", "CSS Flexbox: Container Properties (display: flex, flex-direction)", "Flexbox", "Intermediate"),
        ("html-025", "Flexbox Alignment: justify-content and align-items", "Flexbox", "Intermediate"),
        ("html-026", "Flexbox Item Properties (flex-grow, flex-shrink, flex-basis, order)", "Flexbox", "Intermediate"),
        ("html-027", "CSS Grid: grid-template-columns, grid-template-rows & gap", "CSS Grid", "Intermediate"),
        ("html-028", "Grid Placement: grid-column, grid-row & fr units", "CSS Grid", "Intermediate"),
        ("html-029", "CSS Shadows (box-shadow, text-shadow) & Border Radius", "CSS Styling", "Intermediate"),
        ("html-030", "CSS Gradients (linear-gradient, radial-gradient)", "CSS Styling", "Intermediate"),
        ("html-031", "CSS Pseudo-classes (:hover, :focus, :active, :nth-child)", "CSS Selectors", "Intermediate"),
        ("html-032", "CSS Pseudo-elements (::before, ::after, ::placeholder)", "CSS Selectors", "Intermediate"),
        ("html-033", "Responsive Design: Viewport Meta Tag & Fluid Layouts", "Responsive Design", "Intermediate"),
        ("html-034", "CSS Media Queries (@media (max-width / min-width))", "Responsive Design", "Intermediate"),
        ("html-035", "Mobile-First vs Desktop-First CSS Architecture", "Responsive Design", "Intermediate"),
        # Advanced (36-50)
        ("html-036", "CSS Transitions (transition-property, duration, timing-function)", "Transitions & Animations", "Advanced"),
        ("html-037", "CSS Transforms (translate, rotate, scale, skew)", "Transitions & Animations", "Advanced"),
        ("html-038", "CSS Keyframe Animations (@keyframes, animation properties)", "Transitions & Animations", "Advanced"),
        ("html-039", "CSS Custom Properties / CSS Variables (--primary-color, var())", "Modern CSS", "Advanced"),
        ("html-040", "CSS Clamp(), Min(), and Max() for Fluid Typography", "Modern CSS", "Advanced"),
        ("html-041", "CSS Aspect-Ratio and Object-Fit for Images", "Modern CSS", "Advanced"),
        ("html-042", "Dark Mode Implementation with prefers-color-scheme", "Modern CSS", "Advanced"),
        ("html-043", "HTML5 Audio (<audio>) and Video (<video>) Elements", "HTML5 Media", "Advanced"),
        ("html-044", "HTML5 Canvas Basics (<canvas>)", "HTML5 Graphics", "Advanced"),
        ("html-045", "Web Accessibility (A11y): ARIA Roles, Labels & Keyboard Navigation", "Accessibility", "Advanced"),
        ("html-046", "CSS Specificity & the Cascade Hierarchy (!important, ID, Class, Tag)", "CSS Architecture", "Advanced"),
        ("html-047", "Modern CSS Reset & Normalization Best Practices", "CSS Architecture", "Advanced"),
        ("html-048", "CSS BEM (Block Element Modifier) Naming Methodology", "CSS Architecture", "Advanced"),
        ("html-049", "CSS Container Queries (@container) for Modular Components", "Modern CSS", "Advanced"),
        ("html-050", "Web Performance: Critical CSS, Asset Preloading & Rendering Optimization", "Web Performance", "Advanced"),
    ]
}

print(f"Total Languages: {len(LANG_TOPICS)}")
for lang, topics in LANG_TOPICS.items():
    print(f"Language {lang}: {len(topics)} topics")
